liftoff-team/sarce-trainer-admin

- .travis.yml
- db/seeds.rb
- spec/features/question/edit_question_spec.rb
- spec/features/question/new_question_spec.rb
- spec/support/configs/database_cleaner.rb
> refactor(specs): removes the need for test db seeding

- app/models/question.rb
- spec/models/question_spec.rb
validates there is at least one correct answers
Add correct_answers validtion spec
> test(question): Add minimum length validation

- README.md
[ci skip]
Related to issue #71
> (docs): Improve the Readme

- app/views/admin/documentations/_form.html.haml
- app/views/admin/documentations/edit.html.haml
- app/views/admin/documentations/new.html.haml
Add a basic form for
Add a partial
Related to issue #80 and issue #82
> feat(Documentation): Add new and edit views

- app/assets/stylesheets/global.scss
- app/controllers/admin/daily_questions_controller.rb
- app/views/admin/daily_questions/index.html.haml
Add table that display list of daily_questions
Add link to DailyQuestion#show
Add link to DailyQuestion#edit
Related to issue #85
> feat(DailyQuestion): Add DailyQuestion#index view

- app/views/admin/daily_questions/show.html.haml
Add table to display the dailyquestion
Related to issue #87
> feat(DailyQuestion): Add DailyQuestion#show view

- spec/features/admin/users_index_spec.rb
- spec/features/password_spec.rb
- spec/features/profile_spec.rb
- spec/features/question/edit_question_spec.rb
- spec/features/question/new_question_spec.rb
- spec/features/sign_up_spec.rb
- spec/models/documentation_spec.rb
- spec/models/given_answer_spec.rb
- spec/models/question_spec.rb
- spec/models/user_spec.rb
- Instead of using static path use helper path
- Delete annotate
- Clean background to use only sign_in and visit
Related to issue #108
> refactor(specs): Add rails helper path

- spec/controllers/admin/users_controller_spec.rb
- spec/controllers/my_profiles_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- Add my_profiles, registrations and users spec controllers
issue #103
> test(controller): Add missing spec controllers

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/components/datepicker.coffee
- app/assets/stylesheets/application.scss
- app/views/admin/daily_questions/_form.html.haml
- app/views/admin/daily_questions/edit.html.haml
- app/views/admin/daily_questions/index.html.haml
- app/views/admin/daily_questions/new.html.haml
- app/views/admin/daily_questions/show.html.haml
- config/initializers/assets.rb
- config/locales/en.yml
- config/locales/fr.yml
- Add a basic form for
- Add a partial
- Add datepicker bootstrap
Related to issue #84 and issue #86
> feat(DailyQuestion): Add new and edit views

- config/environments/production.rb
- Set default_url_options[:host]
> fix(environments/production): Add missing host

- app/assets/javascripts/application.js
- app/assets/javascripts/components/datepicker.js.coffee
- app/views/admin/daily_questions/index.html.haml
- Update datepicker file to use coffeescript
- Use 'ready turbolinks:load' instead of method: :get
Related to issue #125
> chore(datepicker): Add in vendor/assets

- app/controllers/admin/users_controller.rb
- Add on user#update @ranks
Related to issue #134
> fix(user): Add on update @ranks

- app/views/layouts/_header.html.haml
> feat(dailyquestions): Add index on the header

- app/views/admin/daily_questions/index.html.haml
- app/views/questions/index.html.haml
- In order to have directly the link  question#show on dailyquestion#index : 
- Delete on dailyquestion#index views dailyquestion#show
- Replace by question#show
- Add table header on question#index 
Related to issue #119
> feat(dailyquestion): Add question#show link

- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- spec/features/question/new_question_spec.rb
- spec/features/sign_up_spec.rb
- Add in a before_action
- Add skip_before_action :authenticate_user!, only: [:index] for home controller
- Update spec/features
Related to issue #103
> feat(application_controller): Add authenticate_user!

- app/controllers/admin/daily_questions_controller.rb
- app/controllers/admin/documentations_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/admin_controller.rb
- app/controllers/questions_controller.rb
- app/views/admin/daily_questions/_form.html.haml
- app/views/admin/users/edit.html.haml
- app/views/devise/confirmations/new.html.haml
- app/views/devise/passwords/edit.html.haml
- app/views/devise/passwords/new.html.haml
- app/views/devise/registrations/_form.html.haml
- app/views/devise/registrations/edit.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/layouts/_header.html.haml
- config/locales/active_record_fr.yml
- config/locales/date_fr.yml
- config/locales/devise_fr.yml
- config/locales/notification_fr.yml
- spec/features/admin/users_index_spec.rb
- Add translation for notice and alert
- Add missing translation
- Add required attribute
Related to issue #115 
---
TODO:
> feat(fr.yml): Add missing translation

- app/controllers/admin/daily_questions_controller.rb
- app/decorators/daily_question_decorator.rb
- app/views/admin/daily_questions/index.html.haml
- spec/decorators/daily_question_decorator_spec.rb
- Change question_id by question.body
- Update the table header by Intitulé de la question
Related to issue #120
> feat(dailyquestion): update table in index

- app/controllers/admin/daily_questions_controller.rb
- app/controllers/admin/documentations_controller.rb
- app/controllers/questions_controller.rb
- app/views/admin/daily_questions/_form.html.haml
- config/locales/fr.yml
- spec/features/admin/daily_question_new_spec.rb
+ implement  assign_question_id method in DailyQuestion controller
+ add limit on 100
+ use it on new and edit views
Related to issue #121
> feat(dailyquestion): add dropdown question +

- app/views/layouts/application.html.haml
> feat(views): center all views content +

- app/decorators/user_decorator.rb
- spec/decorators/user_decorator_spec.rb
+ add spec/decorators/user_decorator_spec file
+ add describe #answered_question_counter
issue #130
> feat(UserDecorator): add #answered_question_counter

- app/models/user.rb
- db/migrate/20160715105057_add_author_to_questions.rb
- db/schema.rb
- spec/models/user_spec.rb
+ add has_many questions in user model
> feat(migration): add author_id in Questions table +

- app/decorators/user_decorator.rb
- spec/decorators/user_decorator_spec.rb
+ add test #questions_counter
+ use in decorators/user_decorator
close issue #129
> feat(decorators): add User#questions_counter +
